## pyproject.toml
## https://github.com/atlassian-api/atlassian-python-api/blob/master/pyproject.toml
[tool.isort]
multi_line_output = 3
length_sort = true

[tool.black]
skip-string-normalization = true
line-length = 100
target-version = ['py311']
# include = '(pycode|integration_test|tests)\/.*(\.py|GET|POST)'
extend-exclude='''(
    mlops
    | postgres_data
)'''

[tool.pylint.messages_control]
disable = '''
    missing-function-docstring,
    missing-final-newline,
    missing-class-docstring,
    missing-module-docstring,
    invalid-name,
    too-few-public-methods,
    redefined-outer-name,
    R0801,
'''
[tool.pylint.MASTER]
# Specify a score threshold to be exceeded before program exits with error.
fail-under = '1.0'
# Ignore specific paths
ignore-paths = [
    "mlops",
    "postgres_data",
]
